#ifndef NSBLUECOMMANDER__H_
#define NSBLUECOMMANDER__H_

typedef enum {
	STATUS_OK = 0,
	STATUS_ACK,
	STATUS_NAK,
	STATUS_UNEXPECTED_RESPONSE,
	STATUS_READ_TIMEOUT,
	STATUS_SERIAL_PORT_ERROR,
	STATUS_OPEN_FILE_FAILED,
	STATUS_COMMAND_ERROR,
	STATUS_PROGRAM_TOO_BIG,
	STATUS_SELECT_ERROR,
	STATUS_RET_SUCCESS,
	STATUS_RET_UNKNOWN_CMD,
	STATUS_RET_INVALID_CMD,
	STATUS_RET_INVALID_ADDR,
	STATUS_RET_FLASH_FAIL,
	STATUS_FTDI_READ_FAIL,
	STATUS_FTDI_WRITE_FAIL
} STATUS_T;

int init_serial_port(const char* port, speed_t speed);


#endif
